### ISSUE TITLE
Script fails each 2 accounts

### ISSUE THREAD

**Issue by SENPAY98K** [ZWhitey/Steam-Auto-Queue#18]
Probably because of the latest high restriction of steamcommunity.
Maybe get cookies from different place like steam-user or steam-session.
![image](https://github.com/ZWhitey/Steam-Auto-Queue/assets/77079047/feda1ff7-371e-43c0-9c71-101ae54a7099)

**Comment by ZWhitey** [comment]
You can change sleep time to 10 secs in `index.js`, I will release new version for this problem.
 https://github.com/ZWhitey/Steam-Auto-Queue/blob/e0e2cbfc4038a4e34dfbcca696f166c26f1dd8f3/index.js#L9

**Comment by SENPAY98K** [comment]
Yes, I figure it out in my own script, but needed like 30+ seconds

**Comment by SENPAY98K** [comment]
Will test that on your script and let you know

**Comment by SENPAY98K** [comment]
> You can change sleep time to 10 secs in `index.js`, I will release new version for this problem.
> 
> https://github.com/ZWhitey/Steam-Auto-Queue/blob/e0e2cbfc4038a4e34dfbcca696f166c26f1dd8f3/index.js#L9

Still error after 2 accounts! its not possible with less then 30 sec

**Comment by ZWhitey** [comment]
I used 8 accounts with sleep 10 sec and it worked. Maybe you have something else sending request to steam?
