### ISSUE TITLE
401 status unauthorized

### ISSUE THREAD

**Issue by avi02** [ZWhitey/Steam-Auto-Queue#25]
When i am trying to run its giving me 401 status unauthorized error
![image](https://github.com/ZWhitey/Steam-Auto-Queue/assets/16477775/e8ed8e45-5d64-401b-81ea-893941ed070d)

**Comment by ZWhitey** [comment]
You can remove `cookies.db` and try it again.

**Comment by ZWhitey** [comment]
try to use [new version](https://github.com/ZWhitey/Steam-Auto-Queue/releases/tag/v2.9.0)

**Comment by avi02** [comment]
thankyou <3
