### ISSUE TITLE
not working in summer sale 2024

### ISSUE THREAD

**Issue by sneaky-0** [ZWhitey/Steam-Auto-Queue#26]
how do i make the script work in the current summer sale 2024 ? it shows error 401 and 200. please help
p.s- i did try removing the cookie.database file and running the script again but it showed the error again
![image](https://github.com/ZWhitey/Steam-Auto-Queue/assets/83300549/958fbdab-3971-488f-96ea-d00e1a88b0c9)

**Comment by ZWhitey** [comment]
try to use [new version](https://github.com/ZWhitey/Steam-Auto-Queue/releases/tag/v2.9.0)

**Comment by Goblincent** [comment]
can u pls tell me how i can run this script in node.js pls help me
