### ISSUE TITLE
[useraccount] undefined

### ISSUE THREAD

**Issue by DoKnocK** [ZWhitey/Steam-Auto-Queue#5]
![image](https://user-images.githubusercontent.com/68970953/177224433-e54c1d3e-6ca5-4804-b4fd-4acbe733b0ed.png)

Would you know what's wrong ? Why does it only say "Undefined" and does nothing ?

My plugin values are set 'TRUE' for:
1. autocard.js
2. clorthax_quest.js

Please help.

**Comment by ZWhitey** [comment]
I think you got an error when login,  could you edit user.js#23 to print more log?
```
user.js L23: console.error(`[${this.data.account}]`, err.message); -> console.error(`[${this.data.account}]`, err);
```

**Comment by DoKnocK** [comment]
I got it to work, retrieved the old autocard.js file from your source.zip and replaced it in the updated pull. Now I'm able to use both autocard.js [discovery q] & clorthax_quest.js on multiple accounts.

Quick question: does this script only support accounts with Steam guard setup ? As in the account which has a Shared secret for me to provide in the config file ?

I actually tried with accounts which just has steam guard enabled on 'email', and the script does prompt, Enter Auth code, but I don't receive any code in my email and then it says either timeout / invalid username password.

Any idea ? 

Thank you for replying so promptly 👍

**Comment by ZWhitey** [comment]
I don't have any account enable steam guard via email, so I never test that. I think I can add this feature later.
you can check [here](https://www.reddit.com/r/SteamBot/comments/3xb1ft/finding_shared_secret_identity_secret_required/) to find your shared secret.

**Comment by DoKnocK** [comment]
Shared secret only generates when an account is 'Protected by Steam Guard Mobile Authenticator'. Finding that isn't an issue for the account which has a MFA file on desktop authenticator or on phone.

I was more curious about the account which receive their auth code only on email when attempted to login.

Would be awesome if you could add that feature as well, so that carding can become more efficient on all the accounts eligible to receive trading cards from discovery queue.

**Comment by ZWhitey** [comment]
I got my shared secret many years ago, I think it's harder to get it now.
I have update login flow for manual login (ask auth code after login), if you are interesting, you can checkout this branch `enhance-login-flow` .
I only test with mobile authenticator, I think email auth work too. If you got any problem just comment here.
If this work correctly, next time I will try to save session to do auto login without shared secret.

**Comment by DoKnocK** [comment]
> 

yea shared secret is harder to get it from iPhone, me and my friend tried yesterday via iExplorer app, doesn't work anymore.
Anyhow, shared secret on [Steam Desktop Authenticator](https://github.com/Jessecar96/SteamDesktopAuthenticator) app works just fine via .mfa file.

@ZWhitey - Do you have a discord so I can show you the email auth thing am talking about ? DM me, DoKnocK#6969

**Comment by DoKnocK** [comment]
@ZWhitey  - [Enhance-login-flow](https://github.com/ZWhitey/Steam-Auto-Queue/tree/enhance-login-flow) works!!!!! 👍 

I modified line # 41 in user.js to show [accountName] when prompting for auth code.

**Before** -  `const authCode = prompt('Enter your auth code from email: ');`

**Now** - ```const authCode = prompt(`Enter your auth code from email [${loginData.accountName}]: `);```

Output: 
![image](https://user-images.githubusercontent.com/68970953/177646998-f9f0c96e-0440-4c7f-ae47-f97b91736a75.png)

### Now I'm able to use accounts with both secret share & with email auth, thanks a ton @ZWhitey !!! 

### Tested with 2 account with email auth from email
![image](https://user-images.githubusercontent.com/68970953/177646002-1d435634-cf79-4a8d-9319-0382e2748da9.png)

**Comment by DoKnocK** [comment]
Is it possible to save the login, so that you don't have to ENTER the auth code from Email every time you run the plugin ?

**Comment by ZWhitey** [comment]
> Is it possible to save the login, so that you don't have to ENTER the auth code from Email every time you run the plugin ?

I think maybe I can save cookie to do this, I expect you can skip login process unless your cookie expired.

**Comment by ZWhitey** [comment]
> Is it possible to save the login, so that you don't have to ENTER the auth code from Email every time you run the plugin ?

I have done this in v2.2.0, you only need to enter auth code once. Although summer event is going to end, you still can use in the future event.

**Comment by DoKnocK** [comment]
>  I have done this in v2.2.0, you only need to enter auth code once. Although summer event is going to end, you still can use in the future event.

I will surely check it out, thanks for the `enhance-login-flow`, helped me to farm some cards on my other accounts (on email auth) as well :)

**Comment by DoKnocK** [comment]
@ZWhitey - You're amazing !!! 

![image](https://user-images.githubusercontent.com/68970953/178106224-17ffc254-fb72-4390-985f-e58d8ad7a83e.png)
